### PR TITLE
fixBug: Conditional Stacked Functions in selecting

### LINKED ISSUE #174: Conditional Stacked Functions in selecting
I see in the readme file [it references](https://github.com/ezSQL/ezsql#example-for-using-prepare-statements-indirectly-with-above-shortcut-sql-methods) that you can use a join in a `selecting` statement, but I can't seem to get it to work. Could someone please show me some examples on how this works? This is what I've tried so far

```php
$results = $this->conn->selecting("me_supplier", "me_supplier.supplier_id, me_supplier.supplier_contact_id, me_contact.contact_name, me_contact.contact_email, me_contact.contact_phone, me_contact.contact_status, me_supplier.supplier_account_code, me_supplier.supplier_website", leftJoin("me_contact", "me_supplier", "contact_id", "supplier_contact_id"));
```

So far this tells me that there are no results, but there definitely are as the following works

```php
$results = $this->conn->selecting("me_supplier", "me_supplier.supplier_id, me_supplier.supplier_contact_id, me_supplier.supplier_account_code, me_supplier.supplier_website");
```

I'm also wanting to be able to add `where` statements in there dynamically based on what a user puts in the URL.

### PR DESCRIPTION
**Pull request by dpDesignz**
Fixes ezSQL#174
Removed check for `$columnFields` being empty, and added dots between table and column names in query builder

### CODE REVIEW

**Comment by dpDesignz** [comment]
@techno-express I've made some more adjustments to the joins to allow more flexibility. For some reason there are conflicts identified by GitHub which aren't in my original code though? Not sure if they're actually an issue or not.

**Comment by techno-express** [comment]
You might want to do an local merge/update off master. I made some psr-2 fixes, commits, that is the reason for the conflicts. 

Also, take a look at how some of the phpunit tests i have for help on constructing/creating your test.

**Comment by dpDesignz** [comment]
Oh, that didn't show up in my sync for some reason. Will try and update my local version (still trying to work out how to do this properly. I use GitHub Desktop.) and then take a look at the changes again :)

**Comment by dpDesignz** [comment]
@techno-express sorry for all the commits. Just getting my head around using the new GitHub desktop interface and my VS-Code config. Finally got it all sorted and fixed all the conflicts as well as some more small bugs I found. 😄 

All ready for merge.

**Comment by techno-express** [comment]
Where is the test? 

Can't really merge until then, someone else might come along raising some issue related to JOINS not working, or whatever. As with others submitting issues, i eventually point them to the tests showing not an issue with library cause the phpunit tests covers that. 

There is no proof showing it works.

**Comment by dpDesignz** [comment]
Sorry, I haven't had a chance to look at how phpunit works and I don't have the time to learn it at this stage. Will just have to leave this for now.

**Comment by techno-express** [comment]
Ok, when you are ready, it's really not that much to learn.

You would just add a method to https://github.com/ezSQL/ezsql/blob/master/tests/mysqli/mysqliTest.php
prefixing `test` to it's name. The actually code would look similar to whatever you have written before.

The phpunit just have many methods to compare what you expect, to what the actually result was, like:
`$this->assertEquals($somethingShouldBe, $actaulDatabaseResult);` // this is the actually test.

Look at https://github.com/ezSQL/ezsql/blob/5971a568bf1868803e46bab61399acc3e1a3f416/tests/mysqli/mysqliTest.php#L320

You would be doing the same example test, but with two tables.

**Pull request closed without merging**
